//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrapeCity.ActiveReports.Designer.Win {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrapeCity.ActiveReports.Designer.Win.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   デザイナについて(&amp;A)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CmdExport {
            get {
                object obj = ResourceManager.GetObject("CmdExport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CmdNewReport {
            get {
                object obj = ResourceManager.GetObject("CmdNewReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CmdOpen {
            get {
                object obj = ResourceManager.GetObject("CmdOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CmdSave {
            get {
                object obj = ResourceManager.GetObject("CmdSave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap CmdSaveAs {
            get {
                object obj = ResourceManager.GetObject("CmdSaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   現在の選択:  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CurrentSelection {
            get {
                return ResourceManager.GetString("CurrentSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ActiveReports 14 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultGroup {
            get {
                return ResourceManager.GetString("DefaultGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規RDLレポート.rdlx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultReportNameRdl {
            get {
                return ResourceManager.GetString("DefaultReportNameRdl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規ページレポート.rdlx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultReportNameRdlx {
            get {
                return ResourceManager.GetString("DefaultReportNameRdlx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規マスターレポート.rdlx-master に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultReportNameRdlxMaster {
            get {
                return ResourceManager.GetString("DefaultReportNameRdlxMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規セクションレポート.rpx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultReportNameRpx {
            get {
                return ResourceManager.GetString("DefaultReportNameRpx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DesignerForm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DesignerFormName {
            get {
                return ResourceManager.GetString("DesignerFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ActiveReports for .NET 14.0J デザイナ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DesignerFormTitle {
            get {
                return ResourceManager.GetString("DesignerFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DirtySign {
            get {
                return ResourceManager.GetString("DirtySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} への変更を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EudUnsavedChangesMessage {
            get {
                return ResourceManager.GetString("EudUnsavedChangesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未保存の変更 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EudUnsavedChangesTitle {
            get {
                return ResourceManager.GetString("EudUnsavedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポート(&amp;E)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   へのエクスポートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportCompleteString {
            get {
                return ResourceManager.GetString("ExportCompleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GroupEditorHide {
            get {
                object obj = ResourceManager.GetObject("GroupEditorHide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap GroupEditorShow {
            get {
                object obj = ResourceManager.GetObject("GroupEditorShow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ヘルプ(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループエディタの非表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HideGroupPanelToolTip {
            get {
                return ResourceManager.GetString("HideGroupPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成(&amp;N)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewToolTip {
            get {
                return ResourceManager.GetString("NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoSelection {
            get {
                return ResourceManager.GetString("NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く(&amp;O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ライブラリとして開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenAsLibrary {
            get {
                return ResourceManager.GetString("OpenAsLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .rdl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RdlExtension {
            get {
                return ResourceManager.GetString("RdlExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .rdlx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RdlxExtension {
            get {
                return ResourceManager.GetString("RdlxExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .rdlx-master に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RdlxMasterExtension {
            get {
                return ResourceManager.GetString("RdlxMasterExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル {0} は有効なレポートファイルではありません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReportIsNotValid {
            get {
                return ResourceManager.GetString("ReportIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .rpx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RpxExtension {
            get {
                return ResourceManager.GetString("RpxExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エンドユーザーデザイナ -  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SampleNameTitle {
            get {
                return ResourceManager.GetString("SampleNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き保存(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存(&amp;A)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RDLレポートファイル (*.rdlx)|*.rdlx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveRdlFilter {
            get {
                return ResourceManager.GetString("SaveRdlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページレポートファイル (*.rdlx)|*.rdlx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveRdlxFilter {
            get {
                return ResourceManager.GetString("SaveRdlxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RDLレポートマスターファイル (*.rdlx-master)|*.rdlx-master に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveRdlxMasterFilter {
            get {
                return ResourceManager.GetString("SaveRdlxMasterFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   rpxファイル|*.rpx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveRpxFilter {
            get {
                return ResourceManager.GetString("SaveRpxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グループエディタの表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowGroupPanelToolTip {
            get {
                return ResourceManager.GetString("ShowGroupPanelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {2} - {0}{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleFormat {
            get {
                return ResourceManager.GetString("TitleFormat", resourceCulture);
            }
        }
    }
}
